### ISSUE TITLE
Multiple canaries for same commit - local

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#1153]
When I try to run `auto canary` twice in a row locally with no changes auto fails to publish a second canary.

**Comment by ChristianUlbrich** [comment]
Although this might be expected behavior. I guess the culprit is, that the version already exists in the package registry and thus subsequent publishing fails. Remedying this would involve doing _either_ a lookup or and I guess this is the _right way_™ _ignoring_ _publish errors_ if the version already exists just for canary builds. This is related to #994

**Comment by hipstersmoothie** [comment]
While the "_right way_™" for the publishing tool might be to warn the user that the version already exists, `auto` has tried to make the publishing experience easier. 

- if you rebuild a PR build a new canary will published because the CI build number is included in the canary version
- if you try to `shipit` and a release exists with a higher version, we use that version

So, in my mind, if `auto` were to check that a canary version exists before publishing, that would be totally in line with what `auto` already does. We could hide this behavior behind a flag and suggest that the user uses the flag, but I can't really think of a situation where I wouldn't want to use it.

One downside to this is that it must be implemented in each plugin. Core itself doesn't really know what the current version is.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.43.0`](https://github.com/intuit/auto/releases/tag/v9.43.0) :rocket:
