### ISSUE TITLE
How do i automatically bump version in package.json with auto?

### ISSUE THREAD

**Issue by RichieRunner** [intuit/auto#1365]
After running `auto shipit` in my CI environment, i notice that the version on my `package.json` is not changing. Shouldn't auto be doing this for me? Or which NPM command do I need to run?

You guys are doing it as well somehow:
![image](https://user-images.githubusercontent.com/20289967/87094848-7c4fb180-c1f4-11ea-86ad-92e6f935fbaa.png)

**Comment by RichieRunner** [comment]
it looks like this can done with [`npm version`](https://docs.npmjs.com/cli/version.html), but I don't see where you guys are calling that in your pipeline?

**Comment by hipstersmoothie** [comment]
The npm plugin should handle this. Can you share your configuration?

**Comment by RichieRunner** [comment]
I didn't install it because:
1) the [doco](https://intuit.github.io/auto/docs/generated/npm) states that the it is already loaded by default
2) I do not want to publish my package to NPM (it is private repo)

Therefore, my `.autorc` config does not have any plugins property declared.

I noticed that the following repos (including this one) is able to achieve the automatic version bump without any explicit reference to the NPM plug:
- https://github.com/artsy/reaction
- https://github.com/apollographql/space-kit
- https://github.com/adierkens/webpack-inject-plugin

**Comment by hipstersmoothie** [comment]
The `npm` plugin is the default plugin (when installed from npm) if no other plugins are specific. but if you add any other plugin the defaults will be overriden.

[Here](https://intuit.github.io/auto/docs/configuration/plugins#using-plugins) it is in the docs. If you think it's kinda hidden feel free to make a PR that makes it a little clearer for you.

**Comment by RichieRunner** [comment]
I was able to achieve this with [this custom bash script](https://intuit.github.io/auto/docs/welcome/getting-started#enabling-skip-release-label). Still have no idea why I have to explicitly do this while other repos don't. Oh well, it works.

**Comment by hipstersmoothie** [comment]
Can you share the repo? I could take a look

**Comment by RichieRunner** [comment]
> Can you share the repo? I could take a look
- https://github.com/intuit/auto
- https://github.com/artsy/reaction
- https://github.com/apollographql/space-kit
- https://github.com/adierkens/webpack-inject-plugin

**Comment by hipstersmoothie** [comment]
Well I know where it works I want to see why *yours* doesn't work

**Comment by hipstersmoothie** [comment]
So either a link to your repo or your autorc.

I can debug what's happening if you provide the command with -vv output.

**Comment by pepf** [comment]
Ran into this as well from a similar angle as topic starter. (I'm willing to update the docs once I know what the "best" solution is here)

I have no npm plugin added, because of a private repo with no "published assets", but "just" dependent on the package.json version being correct while mainly relying on tagging releases using `git-tag` for automation.

```
{
  "plugins": [
    "git-tag"
  ],
  "owner": x
  "repo": x
  "name": x
  "email": "x
  "prereleaseBranches": ["develop"]
}
```
Would you still recommend installing npm plugin (seems to require an npm token, which wouldn't really make sense in my use-case) or does this [exec plugin example](https://intuit.github.io/auto/docs/generated/exec) makes sense perhaps (given its a more "lightweight" version just running `yarn version` at the right time)? 

My goal is exactly like the examples here, just having a _single_ _tagged_ commit that bumps the version and gets tagged on every release.

**Comment by hipstersmoothie** [comment]
@pepf Could you try version `v9.48.0`? You should now be able to switch to the `npm` plugin and it will work with a private npm package 🎉
