### ISSUE TITLE
Auto potentially passing wrong semver information to 'semver' component for comparison, breaks build

### ISSUE THREAD

**Issue by vincentbriglia** [intuit/auto#1443]
**Describe the bug**

Difficult to confirm but it looks like publishing versions on next branch, auto is passing a semver version to compare to "semver" module with package name and that fails a build

**To Reproduce**

https://github.com/LEGO/klik/runs/955803465

**Expected behavior**

semver version passes

**Screenshots**

![image](https://user-images.githubusercontent.com/452811/89590681-ca35f480-d848-11ea-88a0-daae945a35c9.png)

**Environment information:**

see build run

**Comment by vincentbriglia** [comment]
@hipstersmoothie is there an easy way to test auto locally, in dry-run mode, that is equivalent to running it on CI? I haven't really had the chance to deep dive into auto, but am eager to help with issues.

**Comment by hipstersmoothie** [comment]
> is there an easy way to test auto locally, in dry-run mode, that is equivalent to running it on CI? 

This is definitely a limitation of `auto` right now. The `--dry-run` flag makes most command skip calling plugins and instead tries to "guess" what will happen. There is currently an open issue around this #1279. 

Delegating this behavior to the plugins will be a breaking change but I think it's a very valid one. I will add it to my v10 change list #1156 and might work on this soon, as it has been a pain point for a few people.

The way I usaully develop `auto` is I have the project in `build --watch` and use the `../auto/packages/cli/dist/bin/auto.js` to run commands. I'll `process.exit` after the bit i'm working on. Admittedly a better `--dry-run` would help with this too.

Side note: Sorry for all the snags you're hitting with `lerna` independent mode for `next` versions. You might be one of the first people using `auto` like this and I appreciate you posting these issues since I personally don't use independent versioning.

**Comment by adierkens** [comment]
:rocket: Issue was released in [`v9.49.6`](https://github.com/intuit/auto/releases/tag/v9.49.6) :rocket:
