### ISSUE TITLE
autorc option to only make releases when PRs are merged.

### ISSUE THREAD

**Issue by hipstersmoothie** [intuit/auto#210]
**Is your feature request related to a problem? Please describe.**

https://github.com/intuit/auto-release/issues/202#issuecomment-455647188

**Describe the solution you'd like**

`.autorc` option to only make releases when PRs are merged. 

Current behavior is any push to master is treated as a `patch`

this is separate from the `onlyPublishWithRelease` flag. In that mode pushes to master wouldn't be published anyway. This is only when `onlyPublishWithRelease` is not set.

**Comment by aleclarson** [comment]
Maybe the default behavior should be to ignore commits to master that have no PR. For those commits, we could check the commit message for a `fix:` prefix (à la semantic-release) and only _then_ treat it as a patch. **Note:** I'm not suggesting we inspect commit messages for any other prefixes, since all features and breaking changes should be via PR.

**Comment by zephraph** [comment]
@aleclarson seems like a lot... is that something we could do via a plugin?
