### ISSUE TITLE
Custom bump commit message

### ISSUE THREAD

**Issue by aleclarson** [intuit/auto#230]
**Feature:** Add an `.autorc` option for customizing the commit message used by the NPM plugin when it bumps the package version.

```json
{
  "bumpHeader": "{{version}}",
  "bumpFooter": "[skip ci]"
}
```

**Comment by aleclarson** [comment]
I might prefer no bump commits (like `semantic-release` does it):

```json
{
  "bump": false
}
```

With bump commits disabled, the latest NPM version is the source of truth (or maybe it already works that way?) and the "version" field in `package.json` can be set to `0.0.0-development` or similar.

**Comment by hipstersmoothie** [comment]
is skip CI different on travis? without that in your commit messages you can easily fall into a loop

**Comment by aleclarson** [comment]
lol, that's a funny typo. I'd say `shipit` should check if the version in `package.json` is something like `0.0.0-development` and skip creating a bump commit.

**Comment by aleclarson** [comment]
What do you think of `shipit` skipping the bump commit when the version in `package.json` is something like `0.0.0-development`?

**Comment by hipstersmoothie** [comment]
0. Package starts at 0.0.0-development

1. you run `version` it returns the bump based on PRs, it returns anything (patch, minor, major) - lets say it's patch

2. Changelog creation - (0.0.0-development => 0.0.0). But you don't want that to happen? Instead add under the '0.0.0-development' changelog title?

3. publish hooks time - it would 0.0.0-development => 0.0.0 and publish. but you want `development` to be detected and skip publish step all together

4. make a github release - Instead of creating a new release, update the old one with the new commits

**Comment by aleclarson** [comment]
A package with a version of `0.0.0-development` indicates the following:
- The highest published NPM version is considered the "current version"
- The `version` in `package.json` should never be changed

When a new NPM version should be published, Auto should increment the "current version" using `npm version $(auto version)`.

The changelog uses the "current version" from NPM (instead of from `package.json`).

As always, a new Github release is created for every NPM version.

Am I being clear enough?

**Comment by hipstersmoothie** [comment]
> The version in package.json should never be changed

To publish new versions to NPM you have to change this. The only way to increment the "current version" and never change the local one would be to: 

- change it to current version (NPM)
- do the bump
- change it back
- but since it the tag would be the bump current version do ???

---

I'm pretty sure I understand your use case.

a. you don't want to publish a bunch of versions while you are developing a feature over multiple PRS
b. once a new version should be published you want all the changes included

In my eyes we already give you two ways to do this:

1. use `onlyPublishWithReleaseLabel`. new versions aren't created until you add this label. So you could look at any PR/code without the label as `VERSION-development`

2. as you are merging PRs for the big feature use `skip-release` until you are ready for a version, then just merge a PR. The new release contains all skipped PRs. In this case you can look at adding the `skip-release` label as signifying that your version is `VERSION-development`

How does this differ from the behavior you want?

It seem to me to boil down to: you want to add `-development` to your version to start skipping releases and remove it when your ready for all the changes to be released at once.

**Comment by hipstersmoothie** [comment]
to accomplish my last sentence you could probably make a plugin that uses `beforeShipit` to check for the presence `-development` in the version and throws an error if it's present. This would prevent `shipit` from moving forward until you remove `-development`.

The only problem I see with this is that it would also fail the CI job.

**Comment by aleclarson** [comment]
Interesting interpretation, but not quite what I intended. 😅 

I'm basically describing how `semantic-release` works.

I _should_ have said "The version in `package.json` is only changed temporarily in order for `npm publish` to succeed" (instead of "The version in `package.json` should never be changed"). All I'm really trying to do is avoid the permanent bump commit. :)

**Comment by hipstersmoothie** [comment]
Ok so the state you would end up in is:

repo: only ever has verison 0.0.0-dev

npm: Has the real version all the time (this is whats used for anything)

correct?

**Comment by hipstersmoothie** [comment]
Kinda like 

```ts
        if (auto.options.skip) {
          // get published version
          // change local version to publish
        } else {
          await execPromise('npm', [
            'version',
            latestBump || version,
            '-m',
            '"Bump version to: %s [skip ci]"'
          ]);
        }

        await setTokenOnCI();

        await execPromise(
          'npm',
          !isPrivate && isScopedPackage
            ? ['publish', '--access', 'public']
            : ['publish']
        );

        if (auto.options.skip) {
          // change local version back to DEV
        } 

        await execPromise('git', [
          'push',
          '--follow-tags',
          '--set-upstream',
          'origin',
          '$branch'
        ]);
      }
```

**Comment by hipstersmoothie** [comment]
`auto` v4.0.0 here we come lol. Looks like I'm gonna have to split up the `publish` hook. This will be another plugin

**Comment by aleclarson** [comment]
If you want, you could bake this feature into Auto for now, and wait to split the `publish` hook until another plugin needs it too. 😛

**Comment by hipstersmoothie** [comment]
This should be possible via plugin now with #247 (the semver ability). The commit message thing requires a bit of config changes and doesn't really get you much. Closing but open to PRs!
