### ISSUE TITLE
QUESTION: in Lerna monorepo, why do all packages get published when only one is impacted by a change?

### ISSUE THREAD

**Issue by jrnail23** [intuit/auto#748]
I'm using lerna with independent versioning, but I noticed that my PR builds are publishing new canary versions of all my packages, even when only one of them is impacted by a change.

Is this the expected behavior?

Also, FWIW, all packages' versions are getting incremented as well, as if it was using `fixed` versioning.  I've checked my `.autorc.json` file, and I have `npm.forcePublish` set to `false`.

**Comment by hipstersmoothie** [comment]
This is intentional. In my opinion it is easier to consume a canary release under the fixed versioning scheme. One case is say you change you build setup (no package changes), you might want to test those changes, but if you dont `--force-publish` the canary version no version will be published.

https://github.com/intuit/auto/blob/master/plugins/npm/src/index.ts#L473

> all packages' versions are getting incremented as well

is this outside of canaries? I would expect canaries version to all get incremented by the version bump, then once merged only the changed packages are released

**Comment by jrnail23** [comment]
Thanks @hipstersmoothie, sounds like I should also turn off `--force-publish`.
I'll give it another look too.
